// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Aq1WU-v-Qgy_D-Acmzk2SRF-WD6Mg80',
    appId: '1:988044808292:web:e300d60d520ee7c4a20f71',
    messagingSenderId: '988044808292',
    projectId: 'yatin-bike-rent',
    authDomain: 'yatin-bike-rent.firebaseapp.com',
    storageBucket: 'yatin-bike-rent.firebasestorage.app',
    measurementId: 'G-RDPM9QDH8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1g_MZ8MGzF-BREoWt2FmpqFkJzEeYNUU',
    appId: '1:988044808292:android:1f97b1802351c1dba20f71',
    messagingSenderId: '988044808292',
    projectId: 'yatin-bike-rent',
    storageBucket: 'yatin-bike-rent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-zvpJVGhudasj82c5Ep78kU0i5cO3Y3o',
    appId: '1:988044808292:ios:cf86d3a3b02f9752a20f71',
    messagingSenderId: '988044808292',
    projectId: 'yatin-bike-rent',
    storageBucket: 'yatin-bike-rent.firebasestorage.app',
    iosBundleId: 'com.example.hitenBikeRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-zvpJVGhudasj82c5Ep78kU0i5cO3Y3o',
    appId: '1:988044808292:ios:cf86d3a3b02f9752a20f71',
    messagingSenderId: '988044808292',
    projectId: 'yatin-bike-rent',
    storageBucket: 'yatin-bike-rent.firebasestorage.app',
    iosBundleId: 'com.example.hitenBikeRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Aq1WU-v-Qgy_D-Acmzk2SRF-WD6Mg80',
    appId: '1:988044808292:web:76dc1144b5447b42a20f71',
    messagingSenderId: '988044808292',
    projectId: 'yatin-bike-rent',
    authDomain: 'yatin-bike-rent.firebaseapp.com',
    storageBucket: 'yatin-bike-rent.firebasestorage.app',
    measurementId: 'G-EHXL58TFCE',
  );
}
